### ISSUE TITLE
Error Class 'Curl\Curl' not found

### ISSUE THREAD

**Issue by maxodrom** [deka6pb/yii2-geocoder#1]
I am triing to use your yii2-geocoder.
My code is like follow:

``` php
$coder = Geocoder::build(Geocoder::TYPE_YANDEX);
$address =  $companyModel->country->name . ', ' . $companyModel->city->name . ', ' . $companyModel->address;
$object = $coder::findOneByAddress($address);
print_r($object);
```

But it causes error: 
Class 'Curl\Curl' not found
In your package the class does not exist.

Bug?!
https://yadi.sk/i/PsVcGaIWqX7ak

**Comment by deka6pb** [comment]
Thank you for your response. You are right. I forgot to specify a dependency in this library
